### ISSUE TITLE
React-Native与现有APP集成问题

### ISSUE THREAD

**Issue by whwzm88** [vczero/react-native-lession#11]
您好，看到您写的教程，非常浅谈易懂，受益匪浅，目前在感受这个框架的过程中，遇到一个问题

比如，我们已经用安卓原生的开发了一个APP，目前想在APP中，新的模块使用React-Native进行开发，但是老的模块，暂时先保留原样。

通过查看官方的DOC，如下链接：
http://facebook.github.io/react-native/docs/embedded-app-android.html#content

发现按照这个方法，现有的项目会出现编译问题；

不知道您对在现有的APP中，嵌入React-Native，有没有一些心得体会呢，可以推荐一些资料吗？

**Comment by vczero** [comment]
Hi，@whwzm88 可以参考
https://github.com/vczero/react-native-lesson/blob/master/lesson9.md
这样可以保持使用最新版本的ReactNative
