### ISSUE TITLE
init完了，run起来是这样

### ISSUE THREAD

**Issue by kylezhang** [vczero/react-native-lession#18]
init完了，run起来是这样
![qok9w](https://cloud.githubusercontent.com/assets/3679798/12573434/06a5e890-c434-11e5-8aa7-cf494fc9f555.png)

**Comment by sutaking** [comment]
执行一下reload

**Comment by vczero** [comment]
年底太忙了，请详细描述下问题。多谢，：）

**Comment by yeStwind** [comment]
楼主你好，我也遇到了同样的问题，请问解决了吗？
