### ISSUE TITLE
第5篇UI组件问题

### ISSUE THREAD

**Issue by xManApp** [vczero/react-native-lession#2]
第5篇UI组件  按照你的方式我修改了 但是不成功  能不能再详细一点！ 我还是不明白 谢谢高手！

**Comment by vczero** [comment]
Thank you.希望你能成功～
可以按照以下步骤：
（0）默认你node环境安装好了，环境变量可用，可以npm。
（1）拷贝react-native源码：git clone https://github.com/facebook/react-native.git
（2）brew install watchman
（3）brew install flow
（4）安装命令行工具：npm install -g react-native-cli
（5）切换到你需要存放项目的目录 & 创建新项目: react-native init HelloWorld
（4）cd HelloWorld
（5）双击AwesomeProject.xcodeproj在xcode中打开项目
（6）在xcode中运行项目，cmd + R,如果看到欢迎页面（同时还有一个控制台，node启动了8081端口的监控），没有红色报错，说明项目创建成功；
（7）将https://github.com/facebook/react-native/tree/master/Examples/UIExplorer的所有文件拷贝到index.ios.js的同级目录几项目根目录；

两种方式修改demo启动项目：

第一种改文件方式：
（8）用sublime text等文本工具打开index.ios.js.
（9）将UIExplorerApp.js中的内容拷贝并覆盖掉index.ios.js中所有原内容（或者你将UIExplorerApp.js重命名为index.ios.js即可，当然后续的内容改动可以不修改原demo的话，可以拷贝出来）
（10）修改AppRegistry.registerComponent('HelloWorld', () => UIExplorerApp);注意此处是HelloWorld。
（11）这个不需要重启项目，直接在模拟器上cmd + R即可。

第二种：
（8）打开UIExplorerApp.js文件，修改AppRegistry.registerComponent('HelloWorld', () => UIExplorerApp);中的UIExplorerApp为HelloWorld
（9）在xcode中打开AppDelegate,修改jsCodeLocation为jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/UIExplorerApp.bundle"];
（10）这个需要重启项目，退出模拟器和控制台（例如点击模拟器，cmd + Q）；
（11）模拟器和控制台退出后，在xcode上 cmd ＋ R启动项目，即可看到效果。
