### ISSUE TITLE
能否做个 Wiki 出来呢？

### ISSUE THREAD

**Issue by wenquan0hf** [vczero/react-native-lession#21]
我是极客学院Wiki的PM，不知道能不能做个Wiki 放到我们平台。仓库和原文用 GitHub。我提交一个 PR 配置就可以。希望能得到你的同意，让更多的人观看。
React Native 官方文档是我们组织翻译的。目前有很多人需要这个。
我们的网站 : wiki.jikexueyuan.com

**Comment by vczero** [comment]
OK

**Comment by wenquan0hf** [comment]
@vczero  Wiki 已经上线。
上线地址：http://wiki.jikexueyuan.com/project/react-native-lesson/
现在您仓库更新，Wiki 也会同步更新。
有问题可以加我QQ 402480671
感谢!:)
