### ISSUE TITLE
react-native init react 失败

### ISSUE THREAD

**Issue by cgfeel** [vczero/react-native-lession#3]
Mac OSX用户，看这篇教程
http://vczero.github.io/react_native/%E7%AC%AC1%E7%AF%87hello%20react-native.html

每次执行
react-native init react

都卡在这一步
(node-gyp rebuild 2> builderror.log) || (exit 0)

开了VPN不管用，求解？

**Comment by vczero** [comment]
刚才复现了下，node 切换到v0.10.0即可。因为创建项目的时候还是需要node 0.10.0的，后续有些库需要高版本，可以再切回。提给你一个node版本管理工具：
https://github.com/creationix/nvm
https://cnodejs.org/topic/5338c5db7cbade005b023c98

**Comment by cgfeel** [comment]
我将cnpm换回来，就OK了。3Q

**Comment by lrqrun** [comment]
v0.10.0安装react-native时报 npm ERR! Error: No compatible version found: prompt@'^0.2.14'错误，你用的是这个版本吗？我用最新的v0.10.39安装又卡着不动，我也翻墙了。。。

**Comment by vczero** [comment]
翻墙倒不用。npm ERR! Error: No compatible version found: prompt@'^0.2.14'说明prompt模块的0.2.14没有找到。我刚才npm install prompt@0.2.14下，是ok的。如果只有这个库报错，可以单独安装一下试试。关于package.json的依赖版本数字大小说明：http://stackoverflow.com/questions/22343224/difference-between-tilde-and-caret-in-package-json
