### ISSUE TITLE
About Lizard & Mole

### ISSUE THREAD

**Issue by Nirvana-icy** [vczero/react-native-lession#4]
你好 关于718杭州分享PPT.
开发者使用ReactJS开发的应用程序可以转成ReactNative的代码   Lizard
ReactNative的代码可以直接打包成ReactJS前端代码  mole.
很感兴趣 自己是一名Native开发者 正在写RN.

Lizard 和 mole Google了一下没有找到相关信息.可以介绍一下这两个工具吗.谢谢:)

**Comment by vczero** [comment]
@Nirvana-icy 你好，Nirvana-icy！Lizard和mole是我们携程框架部的一个内部框架。Lizard是一个hybird的框架，目前携程各事业部都在用的。mole是我们正在努力研发的框架，致力于打通h5和native代码，mole后期应该是要开源的，但是目前还没有完全做好开源的准备（目前只完成了30%＋，包含文档、站点、委员会审核等）。如果开源了，我再在这issue中@你。

**Comment by Nirvana-icy** [comment]
@vczero 非常感谢您在杭州的分享~
