### ISSUE TITLE
关于图书、RN学习咨询

### ISSUE THREAD

**Issue by blacksunset** [vczero/react-native-lession#8]
TODO:
Lession9: 模块化开发
Lession10: 搭建项目架构
Lession11: 源码分析

**Comment by makao007** [comment]
期待第9和第10课。

**Comment by vczero** [comment]
这个，有些章节已经在图书中。后期考虑换种方式公布出来

**Comment by imwangxuesen** [comment]
zero，你好，现有的章节已经全部学习完毕，能否指点一下，我是一名iOS开发工程师，没有任何的前端web开发经验，现在对这个框架下的应用构建有了大体的了解，对于，JS , react-native facebook 框架的学习，还有css 相关的知识的学习思路非常凌乱，不知道先从哪个入手比较合理，烦请作者能否指导一下学习思路

**Comment by vczero** [comment]
你好@imwangxuesen。  
（1）css的学习大概有80个属性，常用的大概50个以内。周末我整理下，放在这里。  
（2）如果想深入了解css和js，给你个建议：可以尝试先写个web页面熟悉下（主要是练习css样式），js可以学习下基本语法就ok。当然flexbox需要你单独拎出来在React Native上学习，因为React Native的flexbox跟浏览器的flexbox还是有些不同，直接学习就好。  
关于js、布局等相关基础在后续上市的图书《React Native入门与实战》中第二章会有详细的介绍。

**Comment by imwangxuesen** [comment]
@vczero 
谢谢，指点，期待你的整理，你的这本书什么时候上市？我要第一时间买到，求发布公告位置，要是可以提前买到手稿就飞起了，哈哈，yy一下，

**Comment by vczero** [comment]
就在这里公告了。：）

**Comment by imwangxuesen** [comment]
回时刻关注的，昨晚你指点一下茅塞顿开，那我html需不需要学习一下？

**Comment by vczero** [comment]
html基本没有学习的必要。重点看下：JSX的语法规则。往简单的说，就是XML上加属性和事件。JSX is a JavaScript syntax extension that looks similar to XML. You can use a simple JSX syntactic transform with React.
可以戳这：http://facebook.github.io/react/docs/jsx-in-depth.html   深入了解下

**Comment by makao007** [comment]
我之前是搞web开发的，前端后端都有，但没有搞过iOS, 基本的CSS属性我懂，第四章的样式，我是根据效果图，自己一步步写代码的，与你post出来的代码差不多。
但我对navigator之类的组件不熟悉，涉及互交方面的不太了解，能否搞个具体应用剖析一下？
比方说，搞出阅读文章，分类，收藏，搜索，发表评论，下拉更新文章列表，上拉加载更多数据，等等。

**Comment by vczero** [comment]
@makao007 navigator相关的可以参考 https://github.com/vczero/React-LBS  。  关于搜索、列表更新的可以参考：   https://github.com/vczero/React-Dou   。发表参考：通讯录App即可。

**Comment by imwangxuesen** [comment]
get it ，zero你这热心肠我也是通天膜拜，谢谢

**Comment by imwangxuesen** [comment]
@makao007 我觉得咱俩可以互补一下，真的，你怎么看？

**Comment by vczero** [comment]
@imwangxuesen 。目前的支持css样式如下：    

```
var styles =  [
  "alignItems", 
  "alignSelf",
  "backfaceVisibility",
  "backgroundColor",
  "borderBottomColor",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomWidth",
  "borderColor",
  "borderLeftColor",
  "borderLeftWidth",
  "borderRadius",
  "borderRightColor",
  "borderRightWidth",
  "borderStyle",
  "borderTopColor",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopWidth",
  "borderWidth",
  "bottom",
  "color",
  "flex",
  "flexDirection",
  "flexWrap",
  "fontFamily",
  "fontSize",
  "fontStyle",
  "fontWeight",
  "height",
  "justifyContent",
  "left",
  "letterSpacing",
  "lineHeight",
  "margin",
  "marginBottom",
  "marginHorizontal",
  "marginLeft",
  "marginRight",
  "marginTop",
  "marginVertical",
  "opacity",
  "overflow",
  "padding",
  "paddingBottom",
  "paddingHorizontal",
  "paddingLeft",
  "paddingRight",
  "paddingTop",
  "paddingVertical",
  "position",
  "resizeMode",
  "right",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "textAlign",
  "textDecorationColor",
  "textDecorationLine",
  "textDecorationStyle",
  "tintColor",
  "top",
  "transform",
  "transformMatrix",
  "width",
  "writingDirection"
]
```

我想大部分样式是见名知义的，遇到需要写的效果，可以参考该样式表，记得最初版本是80个，目前是67个样式。如果那个不清楚的样式，可以贴在这里，一起讨论。

**Comment by vczero** [comment]
React Native入门与实战》图书预售地址：

 目前京东、互动、天猫均有售  
 http://item.jd.com/11844102.html     (京东自营)  
 http://item.jd.com/10089706582.html  
 http://item.jd.com/10089810271.html       

 ![](http://img12.360buyimg.com/n1/jfs/t2230/225/1782466650/242239/49882b5d/567a1913N46db602f.png)

**Comment by imwangxuesen** [comment]
@vczero 谢谢整理，图书在京东已买，但是显示需要从供应商订货，好像你们和京东的供货环节还有问题没有处理好，迟迟没有发货。

**Comment by vczero** [comment]
@imwangxuesen  谢谢反馈，经出版社反映，图书早已经到了京东，应该是因为京东库存货物太多，没上架。哎...京东这是闹啥样呢！！实在不行，你［退货］吧，换第三方买。目前不少人在第三方已经买到书了（最早的1月4号就拿到书了）。悄悄的告诉你，对了，［当当］也有货。

**Comment by imwangxuesen** [comment]
@vczero 取消了，挺影响你销售的，和京东沟通一下吧

**Comment by vczero** [comment]
@imwangxuesen 嗯嗯，多谢多谢。

**Comment by imwangxuesen** [comment]
@vczero 客气

**Comment by vczero** [comment]
@makao007 
https://github.com/vczero/react-native-lesson/blob/master/lesson9.md
这样可以保持使用最新版本的ReactNative
