### ISSUE TITLE
请问react-native init HelloWorld   xcode里编译不过怎么解决

### ISSUE THREAD

**Issue by zjkdragon** [vczero/react-native-lession#9]
请问我成功创建了一个项目run的时候xcode编译不过，我以前也没接触过ios开发，查了好久没有头绪，请问有遇到和我一样的问题么

**Comment by vczero** [comment]
确保升级xcode了么？可以把Xcode升级到6.4 +。还有可以贴出你的错误信息。

**Comment by bigbig-orange** [comment]
xcode已经是7.1了  好多地方报ecpected a type的错误   google查说是有文件循环引用

**Comment by zjkdragon** [comment]
谢谢  成功了  我升过一次xcode版本  可能是没升级成功  这次编译过了
